import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";
import * as nextAuth from "next-auth/react";
import { InferGetServerSidePropsType } from "next";
import { getPosts } from "./api/posts";

const { useSession, signIn, signOut } = nextAuth;

const Home: NextPage = (
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) => {
  const { posts } = props;
  console.log({ posts });

  const { data: session } = useSession();
  console.log({ session });
  const isLoggedIn = session && session.user;

  const authButton = (
    <a href="#" onClick={() => (isLoggedIn ? signOut() : signIn())}>
      Sign {isLoggedIn ? "out" : "in"}
    </a>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {authButton}
      <div>
        {posts.map((post: any) => {
          return (
            <div key={post.id}>
              <h2>{post.title}</h2>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await getPosts();

  return {
    props: {
      posts: posts.map((post) => ({
        ...post,
        createdAt: post.createdAt.toLocaleString(),
        updatedAt: post.updatedAt.toLocaleString(),
      })),
    },
  };
};

export default Home;
